[package]
name = "django-cli"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap_derive = "4.5.13"
dialoguer = "0.11"
tera = "1.14.1"


[[bin]]
name = "django-cli"
path = "src/main.rs"